version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/openjdk:11-jdk-buster
    steps:
      - add_ssh_keys:  # 🔐 Adds SSH keys from CircleCI Project Settings

      - run:
          name: Add GitHub to known_hosts
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts        

      - checkout

      - run:
          name: Init submodules
          command: |
            git submodule init
            git submodule update --recursive

      - run: mvn clean install