version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/openjdk:11-jdk-buster
    steps:
      - checkout
          submodules: true  # 👈 includes submodules automatically
          
      - run: mvn clean install