version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/openjdk:11-jdk-buster
    steps:
      - checkout
      - run:
          name: Init submodules
          command: |
            git submodule init
            git submodule update --recursive

      - run: mvn clean install