version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/openjdk:11-jdk-buster

    steps:
      - add_ssh_keys  # no colon here

      - run:
          name: Add GitHub to known_hosts
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts

      - checkout

      - run:
          name: Init submodules
          command: |
            git submodule update --init --recursive

      - run: mvn clean install